### ISSUE TITLE
ImportError while running normalSpeed

### ISSUE THREAD

**Issue by wogirzl** [hfutcgncas/normalSpeed#5]
Good morning!

I installed normalSpeed as described, but I am now stuck.
If I run the example.py, I get the following error:

`ImportError: /home/user/.local/lib/python3.6/site-packages/normalSpeed-0.0.1-py3.6-linux-x86_64.egg/normalSpeed.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyThread_tss_get`

This is a similar issue as in this project:  [https://github.com/ga0/pyprotect/issues/11](url)

I've setup normalSpeed with Python 3.6, as well as run it. So it shouldn't be a version issue.
Or do I have to install normalSpeed with >=3.7?

**Comment by wogirzl** [comment]
If you use Python 3.6.9, it's working completely fine. I created first a conda env with pyhton=3.6, which doesn't worked.

**Comment by 0xinit** [comment]
Hey, can you look at one of my issues?

**Comment by wogirzl** [comment]
Sure, not sure if I can solve it, but I can have a look.

**Comment by 0xinit** [comment]
I raised an issue [here](https://github.com/hfutcgncas/normalSpeed/issues/6#issue-963370228)

I have installed pybind11 and opencv3; I still don't know why this error.

**Comment by an99990** [comment]
i have python 3.6.9 and still encounter the issue
![image](https://user-images.githubusercontent.com/87030365/131398218-75fd3a6c-2dec-4ef5-b44b-0bf7c9103f75.png)
